"""Add is_primary and display_order to vehicle_images

Revision ID: 152761acce3c
Revises: 18d6011959b9
Create Date: 2026-01-04 12:46:08.782743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152761acce3c'
down_revision: Union[str, Sequence[str], None] = '18d6011959b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add is_primary column as nullable first
    op.add_column('vehicle_images', sa.Column('is_primary', sa.Boolean(), nullable=True))
    
    # Step 2: Set default value for existing rows
    op.execute("UPDATE vehicle_images SET is_primary = false WHERE is_primary IS NULL")
    
    # Step 3: Make it non-nullable
    op.alter_column('vehicle_images', 'is_primary', nullable=False)
    
    # Step 4: Add display_order column with default
    op.add_column('vehicle_images', sa.Column('display_order', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_images', 'display_order')
    op.drop_column('vehicle_images', 'is_primary')
    # ### end Alembic commands ###
